version: '3'
services:
  speedtest:
    container_name: ${PROJECT_NAME}-speedtest
    image: robinmanuelthiel/speedtest:0.1.1
    restart: always
    depends_on:
      - influxdb
    environment:
      - LOOP=true
      - LOOP_DELAY=${LOOP_DELAY}
      - DB_SAVE=true
      - DB_HOST=http://influxdb:8086
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  influxdb:
    container_name: ${PROJECT_NAME}-influxdb
    image: arm32v7/influxdb:latest
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=${DB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${DB_PASSWORD}
      - INFLUXDB_DB=${DB_NAME}

  chronograf:
    container_name: ${PROJECT_NAME}-chronograf
    image: arm32v7/chronograf:latest
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${DB_USERNAME}
      - INFLUXDB_PASSWORD=${DB_PASSWORD}

  grafana:
    container_name: ${PROJECT_NAME}-grafana
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    user: ${UID}
    volumes:
      - ./data/grafana:/var/lib/grafana

  portainer:
    container_name: ${PROJECT_NAME}-portainer
    image: portainer/portainer-ce:linux-arm
    restart: always
    command: |-
      --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
